# Generated by Django 4.2 on 2025-01-16 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramprofile",
            name="first_name",
            field=models.CharField(
                blank=True,
                help_text="The first name of the Telegram user, stored for personalization purposes.",
                max_length=127,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="telegramprofile",
            name="language_code",
            field=models.CharField(
                blank=True,
                help_text="The preferred language code of the user (e.g., 'en', 'fa'), used to adapt bot responses.",
                max_length=127,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="telegramprofile",
            name="last_name",
            field=models.CharField(
                blank=True,
                help_text="The last name of the Telegram user, stored for personalization purposes (optional).",
                max_length=127,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="telegramprofile",
            name="username",
            field=models.CharField(
                blank=True,
                help_text="The Telegram username of the user, used for easier reference (optional).",
                max_length=127,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="telegramprofile",
            name="telegram_id",
            field=models.CharField(
                help_text="The unique Telegram ID of the user, used for identifying and interacting with them via the bot.",
                max_length=127,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="telegramprofile",
            name="user",
            field=models.OneToOneField(
                help_text="The user associated with this Telegram profile, linking the Telegram account to the system's user.",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="The full name of the user (optional).",
                        max_length=127,
                        null=True,
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True,
                        help_text="The user's date of birth, useful for personalization or age-based features (optional).",
                        null=True,
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="A brief biography or description of the user (optional).",
                        null=True,
                    ),
                ),
                (
                    "height",
                    models.IntegerField(
                        blank=True,
                        help_text="The user's height in centimeters (optional).",
                        null=True,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="A profile image for the user, stored in the 'profile_images' directory (optional).",
                        null=True,
                        upload_to="profile_images",
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(
                        blank=True,
                        help_text="The latitude coordinate of the user's location, used for geolocation features (optional).",
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        blank=True,
                        help_text="The longitude coordinate of the user's location, used for geolocation features (optional).",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="The user associated with this profile, linking additional details to a specific user.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
