# Generated by Django 4.2 on 2025-01-14 14:03

import authentication.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Consumer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "api_key",
                    models.CharField(
                        default=authentication.utils.generate_api_key,
                        max_length=255,
                        unique=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
